'use client';
import { FormEvent, useState } from 'react';

const projects = [
  ['SC01','Campus Climate & Energy Controller','Fuzzy + GA','SC01-Climate-Energy-Controller.md'],['SC02','Smart Washing Machine Optimizer','Fuzzy + GA','SC02-Smart-Washing-Machine.md'],['SC03','Academic Intervention System','Perceptron + ADALINE + BPN','SC03-Academic-Intervention.md'],['SC04','Adaptive Traffic Control','Fuzzy + GA','SC04-Adaptive-Traffic-Control.md'],['SC05','University Timetable Optimizer','Genetic Algorithm','SC05-Timetable-Optimizer.md'],['SC06','Campus Route Optimizer','Genetic Algorithm','SC06-Campus-Route-Optimizer.md'],['SC07','Smart Irrigation System','Fuzzy + ANN','SC07-Smart-Irrigation.md'],['SC08','Predictive Maintenance System','ANN + Fuzzy','SC08-Predictive-Maintenance.md'],['SC09','Credit Risk Decision Support','ANN + Fuzzy','SC09-Credit-Risk.md'],['SC10','Energy Demand & Appliance Scheduler','ANN + GA','SC10-Energy-Scheduler.md'],
];
const base='https://github.com/Galgotias-Projects/Soft-Computing-Capstone-Projects/blob/main/projects/';

export default function Home(){
 const [selected,setSelected]=useState<typeof projects[number]|null>(null); const [message,setMessage]=useState('');
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setMessage('Registration form is ready. Add the Apps Script deployment URL in Netlify to activate live reservations.');}
 return <main><p className="tag">Galgotias University · 2026</p><h1>Soft Computing Project Selection</h1><p>Teams of 3–4 · first come, first served · two teams per project</p><p>Read the complete project specification before registering your team.</p>
 <div className="grid">{projects.map(x=><section className="card" key={x[0]}><b>{x[0]}</b><h2>{x[1]}</h2><p>{x[2]} · <span className="tag">2 team slots</span></p><a href={base+x[3]} target="_blank" rel="noreferrer">Read full specification ↗</a><button onClick={()=>{setSelected(x);setMessage('')}}>Register team</button></section>)}</div>
 {selected&&<div className="backdrop"><section className="form"><button className="close" onClick={()=>setSelected(null)}>×</button><p className="tag">Registering for {selected[0]}</p><h2>{selected[1]}</h2><form onSubmit={submit}><label>Team name<input required placeholder="Example: Fuzzy Pioneers"/></label><label>Team leader name<input required placeholder="Full name"/></label><label>University email<input required type="email" placeholder="name@university.edu"/></label><label>Student ID<input required placeholder="Student ID"/></label><label>GitHub username<input required placeholder="GitHub username"/></label><label>Other members (name, email, ID, GitHub username)<textarea required rows={5} placeholder="Member 2: ...&#10;Member 3: ...&#10;Member 4 (optional): ..."/></label><label className="check"><input required type="checkbox"/> I confirm that my 3–4 member team has read the specification.</label><button type="submit">Reserve team slot</button></form>{message&&<p className="message">{message}</p>}</section></div>}</main>
}
